### ISSUE TITLE
new tagged release?

### ISSUE THREAD

**Issue by sbrun** [trailofbits/onesixtyone#17]
Hi,
It would be great if you could make a tagged release.
I would like to update the Debian package (it's still version 0.3.2) and the packaging tools works best with tagged release: we have tools that monitors web pages listing release, and it works well with github pages showing git tags.
Thanks!

**Comment by dguido** [comment]
Thanks, that's a great idea. I'll ask someone on the team to follow up on it within a day or two.

**Comment by woodruffw** [comment]
Well, it's a little late, but I've cut 0.3.4 as a new release.
